matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

sudo: required

before_install:
  - sudo apt-get install zlib1g-dev
  - sudo apt-get install libglu1-mesa-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
install:

  # Download and unpack a specific version of cmake
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  # Go to the Root directory  
  - cd ..

# Build steps
script:
  - ./build.sh
  - cd framework/cmake
  - ./amorphous-core-test
